export const CossackNames = [
  { forename: { male: 'Albert', female: 'Alla' }, surname: { native: 'Chornovil', helveczian: 'Chornovil' } },
  { forename: { male: 'Ananii', female: 'Anastasiia' }, surname: { native: 'Chornyi', helveczian: 'Chornyi' } },
  { forename: { male: 'Anatolii', female: 'Anhelina' }, surname: { native: 'Dobroshtan', helveczian: 'Dobroshtan' } },
  { forename: { male: 'Andrii', female: 'Anzhela' }, surname: { native: 'Dobryivechir', helveczian: 'Dobryivechir' } },
  { forename: { male: 'Anton', female: 'Antonina' }, surname: { native: 'Holodryga', helveczian: 'Holodryga' } },
  { forename: { male: 'Arkadii', female: 'Bronislava' }, surname: { native: 'Hryzydub', helveczian: 'Hryzydub' } },
  { forename: { male: 'Arsen', female: 'Valentyna' }, surname: { native: 'Kandyba', helveczian: 'Kandyba' } },
  { forename: { male: 'Artem', female: 'Varvara' }, surname: { native: 'Krivoshapka', helveczian: 'Krivoshapka' } },
  { forename: { male: 'Artur', female: 'Vasylyna' }, surname: { native: 'Krutyvus', helveczian: 'Krutyvus' } },
  { forename: { male: 'Atanasii', female: 'Veronika' }, surname: { native: 'Kryvonis', helveczian: 'Kryvonis' } },
  { forename: { male: 'Bohdan', female: 'Viktoriia' }, surname: { native: 'Lomachenko', helveczian: 'Lomachenko' } },
  { forename: { male: 'Borys', female: 'Vira' }, surname: { native: "Lupybat'ko", helveczian: "Lupybat'ko" } },
  { forename: { male: 'Bronislav', female: 'Halyna' }, surname: { native: 'Molyboha', helveczian: 'Molyboha' } },
  { forename: { male: 'Vadym', female: 'Hanna' }, surname: { native: 'Navarykasha', helveczian: 'Navarykasha' } },
  { forename: { male: 'Valentyn', female: 'Daryna' }, surname: { native: 'Nebaba', helveczian: 'Nebaba' } },
  { forename: { male: 'Valerii', female: 'Dariia' }, surname: { native: 'Nedaivoda', helveczian: 'Nedaivoda' } },
  { forename: { male: "Vasyl'", female: 'Dina' }, surname: { native: 'Nepyipyvo', helveczian: 'Nepyipyvo' } },
  {
    forename: { male: 'Viktor', female: 'Emiliia' },
    surname: { native: 'Neschadymenko', helveczian: 'Neschadymenko' },
  },
  { forename: { male: 'Vitalii', female: 'Yeva' }, surname: { native: 'Nesviatypaska', helveczian: 'Nesviatypaska' } },
  { forename: { male: 'Vladyslav', female: 'Yevdokiia' }, surname: { native: 'Netudyhata', helveczian: 'Netudyhata' } },
  { forename: { male: 'Vladlen', female: 'Yevheniia' }, surname: { native: 'Neizhkasha', helveczian: 'Neizhkasha' } },
  {
    forename: { male: 'Volodymyr', female: 'Yelyzaveta' },
    surname: { native: 'Nezdiimynoha', helveczian: 'Nezdiimynoha' },
  },
  {
    forename: { male: 'Vsevolod', female: 'Yefrosyniia' },
    surname: { native: 'Obbizhysvit', helveczian: 'Obbizhysvit' },
  },
  { forename: { male: 'Viacheslav', female: 'Zinaida' }, surname: { native: 'Otchenash', helveczian: 'Otchenash' } },
  {
    forename: { male: 'Hennadii', female: 'Zlata' },
    surname: { native: "Panibud'laska", helveczian: "Panibud'laska" },
  },
  { forename: { male: 'Hryhorii', female: 'Zoriana' }, surname: { native: 'Perebiinis', helveczian: 'Perebiinis' } },
  {
    forename: { male: 'Davyd', female: 'Zoia' },
    surname: { native: 'Perevernykruchenko', helveczian: 'Perevernykruchenko' },
  },
  { forename: { male: 'Danylo', female: 'Ivanna' }, surname: { native: 'Pidipryhora', helveczian: 'Pidipryhora' } },
  { forename: { male: 'Demian', female: 'Inna' }, surname: { native: 'Pidkuimuha', helveczian: 'Pidkuimuha' } },
  { forename: { male: 'Denys', female: 'Iryna' }, surname: { native: 'Podlipa', helveczian: 'Podlipa' } },
  { forename: { male: 'Dmytro', female: 'Kateryna' }, surname: { native: "Pokyn'boroda", helveczian: "Pokyn'boroda" } },
  { forename: { male: 'Eduard', female: 'Klavdiia' }, surname: { native: 'Salohub', helveczian: 'Salohub' } },
  { forename: { male: 'Yevhen', female: 'Larysa' }, surname: { native: 'Sorokopud', helveczian: 'Sorokopud' } },
  { forename: { male: 'Zinovii', female: 'Leonida' }, surname: { native: 'Tiahnyriadno', helveczian: 'Tiahnyriadno' } },
  { forename: { male: 'Ivan', female: 'Lidiia' }, surname: { native: 'Ubyivovk', helveczian: 'Ubyivovk' } },
  { forename: { male: 'Ihor', female: 'Liliia' }, surname: { native: 'Uvorvykishki', helveczian: 'Uvorvykishki' } },
  { forename: { male: 'Illia', female: 'Liubov' }, surname: { native: 'Voshkolup', helveczian: 'Voshkolup' } },
  { forename: { male: 'Yosyp', female: 'Liudmyla' }, surname: { native: 'Vyrvykhvist', helveczian: 'Vyrvykhvist' } },
  { forename: { male: 'Kazymyr', female: 'Maia' }, surname: { native: 'Vernydub', helveczian: 'Vernydub' } },
  { forename: { male: 'Kyrylo', female: 'Marharyta' }, surname: { native: 'Vernyhora', helveczian: 'Vernyhora' } },
  {
    forename: { male: 'Kostiantyn', female: 'Maryna' },
    surname: { native: 'Zapliuisvichka', helveczian: 'Zapliuisvichka' },
  },
  { forename: { male: 'Kuzma', female: 'Mariia' }, surname: { native: 'Zhuivoda', helveczian: 'Zhuivoda' } },
  { forename: { male: 'Lev', female: 'Marfa' }, surname: { native: 'Chornovil', helveczian: 'Chornovil' } },
  { forename: { male: 'Leonid', female: 'Melaniia' }, surname: { native: 'Chornyi', helveczian: 'Chornyi' } },
  { forename: { male: 'Leontii', female: 'Myroslava' }, surname: { native: 'Dobroshtan', helveczian: 'Dobroshtan' } },
  {
    forename: { male: 'Liubomyr', female: 'Mykhaylyna' },
    surname: { native: 'Dobryivechir', helveczian: 'Dobryivechir' },
  },
  { forename: { male: 'Maksym', female: 'Nadiia' }, surname: { native: 'Holodryga', helveczian: 'Holodryga' } },
  { forename: { male: 'Markiian', female: 'Nataliia' }, surname: { native: 'Hryzydub', helveczian: 'Hryzydub' } },
  { forename: { male: 'Marko', female: 'Nina' }, surname: { native: 'Kandyba', helveczian: 'Kandyba' } },
  { forename: { male: 'Marian', female: 'Oksana' }, surname: { native: 'Krivoshapka', helveczian: 'Krivoshapka' } },
  { forename: { male: 'Matvii', female: 'Oleksandra' }, surname: { native: 'Krutyvus', helveczian: 'Krutyvus' } },
  { forename: { male: 'Mykyta', female: 'Olena' }, surname: { native: 'Kryvonis', helveczian: 'Kryvonis' } },
  { forename: { male: 'Mykola', female: "Ol'ha" }, surname: { native: 'Lomachenko', helveczian: 'Lomachenko' } },
  { forename: { male: 'Myron', female: 'Paraskoviia' }, surname: { native: "Lupybat'ko", helveczian: "Lupybat'ko" } },
  { forename: { male: 'Myroslav', female: 'Pelaheia' }, surname: { native: 'Molyboha', helveczian: 'Molyboha' } },
  { forename: { male: 'Mykhaylo', female: 'Raisa' }, surname: { native: 'Navarykasha', helveczian: 'Navarykasha' } },
  { forename: { male: 'Nazar', female: 'Romana' }, surname: { native: 'Nebaba', helveczian: 'Nebaba' } },
  { forename: { male: 'Nariman', female: 'Ruslana' }, surname: { native: 'Nedaivoda', helveczian: 'Nedaivoda' } },
  { forename: { male: 'Oleh', female: 'Svitlana' }, surname: { native: 'Nepyipyvo', helveczian: 'Nepyipyvo' } },
  {
    forename: { male: 'Oleksandr', female: 'Sviatoslava' },
    surname: { native: 'Neschadymenko', helveczian: 'Neschadymenko' },
  },
  {
    forename: { male: 'Oleksii', female: 'Snizhana' },
    surname: { native: 'Nesviatypaska', helveczian: 'Nesviatypaska' },
  },
  { forename: { male: 'Omelian', female: 'Solomiia' }, surname: { native: 'Netudyhata', helveczian: 'Netudyhata' } },
  { forename: { male: 'Orest', female: 'Sofiia' }, surname: { native: 'Neizhkasha', helveczian: 'Neizhkasha' } },
  { forename: { male: 'Ostap', female: 'Stefaniia' }, surname: { native: 'Nezdiimynoha', helveczian: 'Nezdiimynoha' } },
  { forename: { male: 'Pavlo', female: 'Taisiia' }, surname: { native: 'Obbizhysvit', helveczian: 'Obbizhysvit' } },
  { forename: { male: 'Petro', female: 'Tamara' }, surname: { native: 'Otchenash', helveczian: 'Otchenash' } },
  { forename: { male: 'Pylyp', female: 'Teklia' }, surname: { native: "Panibud'laska", helveczian: "Panibud'laska" } },
  { forename: { male: 'Roman', female: 'Tetiana' }, surname: { native: 'Perebiinis', helveczian: 'Perebiinis' } },
  {
    forename: { male: 'Rostyslav', female: 'Uliana' },
    surname: { native: 'Perevernykruchenko', helveczian: 'Perevernykruchenko' },
  },
  { forename: { male: 'Ruslan', female: 'Fedora' }, surname: { native: 'Pidipryhora', helveczian: 'Pidipryhora' } },
  { forename: { male: 'Rustem', female: 'Khrystyna' }, surname: { native: 'Pidkuimuha', helveczian: 'Pidkuimuha' } },
  { forename: { male: 'Sava', female: 'Yuliia' }, surname: { native: 'Podlipa', helveczian: 'Podlipa' } },
  {
    forename: { male: 'Sviatoslav', female: 'Yanina' },
    surname: { native: "Pokyn'boroda", helveczian: "Pokyn'boroda" },
  },
  { forename: { male: 'Semen', female: 'Yaroslava' }, surname: { native: 'Salohub', helveczian: 'Salohub' } },
  { forename: { male: 'Serhii', female: 'Alla' }, surname: { native: 'Sorokopud', helveczian: 'Sorokopud' } },
  {
    forename: { male: 'Stanyslav', female: 'Anastasiia' },
    surname: { native: 'Tiahnyriadno', helveczian: 'Tiahnyriadno' },
  },
  { forename: { male: 'Stepan', female: 'Anhelina' }, surname: { native: 'Ubyivovk', helveczian: 'Ubyivovk' } },
  { forename: { male: 'Taras', female: 'Anzhela' }, surname: { native: 'Uvorvykishki', helveczian: 'Uvorvykishki' } },
  { forename: { male: 'Tymofii', female: 'Antonina' }, surname: { native: 'Voshkolup', helveczian: 'Voshkolup' } },
  { forename: { male: 'Tymur', female: 'Bronislava' }, surname: { native: 'Vyrvykhvist', helveczian: 'Vyrvykhvist' } },
  { forename: { male: 'Trokhym', female: 'Valentyna' }, surname: { native: 'Vernydub', helveczian: 'Vernydub' } },
  { forename: { male: 'Fedir', female: 'Varvara' }, surname: { native: 'Vernyhora', helveczian: 'Vernyhora' } },
  {
    forename: { male: 'Feodosii', female: 'Vasylyna' },
    surname: { native: 'Zapliuisvichka', helveczian: 'Zapliuisvichka' },
  },
  { forename: { male: 'Frants', female: 'Veronika' }, surname: { native: 'Zhuivoda', helveczian: 'Zhuivoda' } },
  { forename: { male: 'Yurii', female: 'Viktoriia' }, surname: { native: 'Chornovil', helveczian: 'Chornovil' } },
  { forename: { male: 'Yukhym', female: 'Vira' }, surname: { native: 'Chornyi', helveczian: 'Chornyi' } },
  { forename: { male: 'Yakiv', female: 'Halyna' }, surname: { native: 'Dobroshtan', helveczian: 'Dobroshtan' } },
  { forename: { male: 'Yaroslav', female: 'Hanna' }, surname: { native: 'Dobryivechir', helveczian: 'Dobryivechir' } },
];
