export const DutchNames = [
  { forename: { male: 'Aart', female: 'Ada' }, surname: { native: 'Baack', helveczian: 'Baack' } },
  { forename: { male: 'Adrianus', female: 'Adriana' }, surname: { native: 'Baas', helveczian: 'Baas' } },
  { forename: { male: 'Aernout', female: 'Agatha' }, surname: { native: 'Bakker', helveczian: 'Bakker' } },
  { forename: { male: 'Aert', female: 'Aleida' }, surname: { native: 'Beekhof', helveczian: 'Beekhof' } },
  { forename: { male: 'Albertus', female: 'Aletta' }, surname: { native: 'Beenhouwer', helveczian: 'Beenhouwer' } },
  { forename: { male: 'Alexander', female: 'Alida' }, surname: { native: 'Bergsma', helveczian: 'Bergsma' } },
  { forename: { male: 'Andreas', female: 'Amalia' }, surname: { native: 'Berkenbosch', helveczian: 'Berkenbosch' } },
  { forename: { male: 'Andries', female: 'Anna' }, surname: { native: 'Boersma', helveczian: 'Boersma' } },
  { forename: { male: 'Antoon', female: 'Anne' }, surname: { native: 'Boogaard', helveczian: 'Boogaard' } },
  { forename: { male: 'Arend', female: 'Anneke' }, surname: { native: 'Boogman', helveczian: 'Boogman' } },
  { forename: { male: 'Arie', female: 'Anneliese' }, surname: { native: 'Boonstra', helveczian: 'Boonstra' } },
  { forename: { male: 'Arjan', female: 'Annemarie' }, surname: { native: 'Bos', helveczian: 'Bos' } },
  { forename: { male: 'Arno', female: 'Annemieke' }, surname: { native: 'Bosch', helveczian: 'Bosch' } },
  { forename: { male: 'Arnout', female: 'Annette' }, surname: { native: 'Bosma', helveczian: 'Bosma' } },
  { forename: { male: 'Axel', female: 'Annie' }, surname: { native: 'Boswel', helveczian: 'Boswel' } },
  { forename: { male: 'Barend', female: 'Annika' }, surname: { native: 'Botha', helveczian: 'Botha' } },
  { forename: { male: 'Bartholomeus', female: 'Anouk' }, surname: { native: 'Bouma', helveczian: 'Bouma' } },
  { forename: { male: 'Bas', female: 'Ans' }, surname: { native: 'Bouwman', helveczian: 'Bouwman' } },
  { forename: { male: 'Bastiaan', female: 'Antje' }, surname: { native: 'Braam', helveczian: 'Braam' } },
  { forename: { male: 'Bauke', female: 'Antonia' }, surname: { native: 'Brouwer', helveczian: 'Brouwer' } },
  { forename: { male: 'Berend', female: 'Astrid' }, surname: { native: 'Bruinsma', helveczian: 'Bruinsma' } },
  { forename: { male: 'Bernardus', female: 'Babette' }, surname: { native: 'Citröen', helveczian: 'Citröen' } },
  { forename: { male: 'Bernhard', female: 'Barbara' }, surname: { native: 'Cornelissen', helveczian: 'Cornelissen' } },
  { forename: { male: 'Bertus', female: 'Beatrix' }, surname: { native: 'De Vries', helveczian: 'De Vries' } },
  { forename: { male: 'Boudewijn', female: 'Carla' }, surname: { native: 'Dekker', helveczian: 'Dekker' } },
  { forename: { male: 'Bram', female: 'Carlijn' }, surname: { native: 'Dhont', helveczian: 'Dhont' } },
  { forename: { male: 'Calvin', female: 'Carolien' }, surname: { native: 'Dierckx', helveczian: 'Dierckx' } },
  { forename: { male: 'Carel', female: 'Carolijn' }, surname: { native: 'Dievoort', helveczian: 'Dievoort' } },
  { forename: { male: 'Carolus', female: 'Caroline' }, surname: { native: 'Dijkgraaf', helveczian: 'Dijkgraaf' } },
  { forename: { male: 'Christiaan', female: 'Catharina' }, surname: { native: 'Dijkman', helveczian: 'Dijkman' } },
  { forename: { male: 'Christoffel', female: 'Charlotte' }, surname: { native: 'Dijkmans', helveczian: 'Dijkmans' } },
  { forename: { male: 'Claes', female: 'Claudia' }, surname: { native: 'Dijksma', helveczian: 'Dijksma' } },
  { forename: { male: 'Clemens', female: 'Cobie' }, surname: { native: 'Dijkstra', helveczian: 'Dijkstra' } },
  { forename: { male: 'Coen', female: 'Cor' }, surname: { native: 'Dijkstra', helveczian: 'Dijkstra' } },
  { forename: { male: 'Cor', female: 'Cornelia' }, surname: { native: 'Duits', helveczian: 'Duits' } },
  { forename: { male: 'Cornelis', female: 'Corrie' }, surname: { native: 'Dykema', helveczian: 'Dykema' } },
  { forename: { male: 'Daniël', female: 'Cynthia' }, surname: { native: 'Dykstra', helveczian: 'Dykstra' } },
  { forename: { male: 'Derk', female: 'Daniëlle' }, surname: { native: 'Elzinga', helveczian: 'Elzinga' } },
  { forename: { male: 'Diederik', female: 'Dora' }, surname: { native: 'Feenstra', helveczian: 'Feenstra' } },
  { forename: { male: 'Dolf', female: 'Dorothea' }, surname: { native: 'Fisser', helveczian: 'Fisser' } },
  { forename: { male: 'Douwe', female: 'Doutzen' }, surname: { native: 'Flinck', helveczian: 'Flinck' } },
  { forename: { male: 'Dries', female: 'Eefje' }, surname: { native: 'Freese', helveczian: 'Freese' } },
  { forename: { male: 'Duif', female: 'Elke' }, surname: { native: 'Friis', helveczian: 'Friis' } },
  { forename: { male: 'Eduard', female: 'Ellen' }, surname: { native: 'Gerbrandy', helveczian: 'Gerbrandy' } },
  { forename: { male: 'Egbert', female: 'Elly' }, surname: { native: 'Groot', helveczian: 'Groot' } },
  { forename: { male: 'Egon', female: 'Els' }, surname: { native: 'Heerma', helveczian: 'Heerma' } },
  { forename: { male: 'Elbert', female: 'Emma' }, surname: { native: 'Hendriks', helveczian: 'Hendriks' } },
  { forename: { male: 'Emiel', female: 'Esther' }, surname: { native: 'Hendriksen', helveczian: 'Hendriksen' } },
  { forename: { male: 'Evert', female: 'Eva' }, surname: { native: 'Hendrix', helveczian: 'Hendrix' } },
  { forename: { male: 'Ewout', female: 'Famke' }, surname: { native: 'Hoebee', helveczian: 'Hoebee' } },
  { forename: { male: 'Floris', female: 'Femke' }, surname: { native: 'Hoebeek', helveczian: 'Hoebeek' } },
  { forename: { male: 'Franciscus', female: 'Fleur' }, surname: { native: 'Hoekstra', helveczian: 'Hoekstra' } },
  { forename: { male: 'Frederik', female: 'Floortje' }, surname: { native: 'Idema', helveczian: 'Idema' } },
  { forename: { male: 'Gabriël', female: 'Frida' }, surname: { native: 'Jansen', helveczian: 'Jansen' } },
  { forename: { male: 'Geert', female: 'Geerten' }, surname: { native: 'JansenBakker', helveczian: 'JansenBakker' } },
  { forename: { male: 'Gerard', female: 'Geertruida' }, surname: { native: 'Jansma', helveczian: 'Jansma' } },
  { forename: { male: 'Gerbrand', female: 'Gerarda' }, surname: { native: 'Janssen', helveczian: 'Janssen' } },
  { forename: { male: 'Gerhardus', female: 'Gerda' }, surname: { native: 'Jenson', helveczian: 'Jenson' } },
  { forename: { male: 'Gerrit', female: 'Gerrie' }, surname: { native: 'Jenssen', helveczian: 'Jenssen' } },
  { forename: { male: 'Gert', female: 'Gesina' }, surname: { native: 'Jorritsma', helveczian: 'Jorritsma' } },
  { forename: { male: 'Gerwin', female: 'Greet' }, surname: { native: 'Jung', helveczian: 'Jung' } },
  { forename: { male: 'Giel', female: 'Grietje' }, surname: { native: 'Kingma', helveczian: 'Kingma' } },
  { forename: { male: 'Gijs', female: 'Hanneke' }, surname: { native: 'Kneijnsberg', helveczian: 'Kneijnsberg' } },
  { forename: { male: 'Gijsbert', female: 'Hansje' }, surname: { native: 'Kneynsberg', helveczian: 'Kneynsberg' } },
  { forename: { male: 'Godfried', female: 'Heidi' }, surname: { native: 'Koopman', helveczian: 'Koopman' } },
  { forename: { male: 'Goos', female: 'Heleen' }, surname: { native: 'Lange', helveczian: 'Lange' } },
  { forename: { male: 'Govert', female: 'Helga' }, surname: { native: 'Lievens', helveczian: 'Lievens' } },
  {
    forename: { male: 'Gregoor', female: 'Hendrika' },
    surname: { native: 'Maarschalkerweerd', helveczian: 'Maarschalkerweerd' },
  },
  { forename: { male: 'Guus', female: 'Hennie' }, surname: { native: 'Meijer', helveczian: 'Meijer' } },
  { forename: { male: 'Hansje', female: 'Henriëtte' }, surname: { native: 'Meijer', helveczian: 'Meijer' } },
  { forename: { male: 'Harmen', female: 'Hilda' }, surname: { native: 'Mesman', helveczian: 'Mesman' } },
  { forename: { male: 'Harrie', female: 'Ilse' }, surname: { native: 'Meulenbelt', helveczian: 'Meulenbelt' } },
  { forename: { male: 'Hein', female: 'Ineke' }, surname: { native: 'Meyer', helveczian: 'Meyer' } },
  { forename: { male: 'Heinke', female: 'Inge' }, surname: { native: 'Molenaar', helveczian: 'Molenaar' } },
  { forename: { male: 'Helge', female: 'Ingrid' }, surname: { native: 'Muis', helveczian: 'Muis' } },
  { forename: { male: 'Hendrikus', female: 'Irene' }, surname: { native: 'Mulder', helveczian: 'Mulder' } },
  { forename: { male: 'Henk', female: 'Jacoba' }, surname: { native: 'Mulder', helveczian: 'Mulder' } },
  { forename: { male: 'Hennie', female: 'Jacqueline' }, surname: { native: 'Peeters', helveczian: 'Peeters' } },
  { forename: { male: 'Hubertus', female: 'Janneke' }, surname: { native: 'Peters', helveczian: 'Peters' } },
  { forename: { male: 'Huib', female: 'Jet' }, surname: { native: 'Pinxten', helveczian: 'Pinxten' } },
  { forename: { male: 'Ivo', female: 'Jo' }, surname: { native: 'Poels', helveczian: 'Poels' } },
  { forename: { male: 'Jacobus', female: 'Johanna' }, surname: { native: 'Posthumus', helveczian: 'Posthumus' } },
  { forename: { male: 'Jan', female: 'Joke' }, surname: { native: 'Postma', helveczian: 'Postma' } },
  { forename: { male: 'Jannes', female: 'Jolanda' }, surname: { native: 'Prins', helveczian: 'Prins' } },
  { forename: { male: 'Jasper', female: 'Jolijn' }, surname: { native: 'Putzeys', helveczian: 'Putzeys' } },
  { forename: { male: 'Jef', female: 'Jorien' }, surname: { native: 'Reitsma', helveczian: 'Reitsma' } },
  { forename: { male: 'Jelle', female: 'Josephina' }, surname: { native: 'Rolloos', helveczian: 'Rolloos' } },
  { forename: { male: 'Jeroen', female: 'Josephine' }, surname: { native: 'Ruis', helveczian: 'Ruis' } },
  { forename: { male: 'Jochem', female: 'Judith' }, surname: { native: 'Ruisch', helveczian: 'Ruisch' } },
  { forename: { male: 'Joep', female: 'Karen' }, surname: { native: 'Ruys', helveczian: 'Ruys' } },
  { forename: { male: 'Joeri', female: 'Karien' }, surname: { native: 'Ruysch', helveczian: 'Ruysch' } },
  { forename: { male: 'Joop', female: 'Karin' }, surname: { native: 'Rynsburger', helveczian: 'Rynsburger' } },
  { forename: { male: 'Jorien', female: 'Karlijn' }, surname: { native: 'Sikma', helveczian: 'Sikma' } },
  { forename: { male: 'Joris', female: 'Karolien' }, surname: { native: 'Smit', helveczian: 'Smit' } },
  { forename: { male: 'Jorrit', female: 'Katja' }, surname: { native: 'Smits', helveczian: 'Smits' } },
  { forename: { male: 'Jozef', female: 'Kornelia' }, surname: { native: 'Spaans', helveczian: 'Spaans' } },
  { forename: { male: 'Jurjen', female: 'Kristi' }, surname: { native: 'Spoelstra', helveczian: 'Spoelstra' } },
  { forename: { male: 'Karel', female: 'Kristin' }, surname: { native: 'Stegenga', helveczian: 'Stegenga' } },
  { forename: { male: 'Karl', female: 'Leonore' }, surname: { native: 'Stoepker', helveczian: 'Stoepker' } },
  { forename: { male: 'Kees', female: 'Lieke' }, surname: { native: 'Terpstra', helveczian: 'Terpstra' } },
  { forename: { male: 'Klaas', female: 'Liesbeth' }, surname: { native: 'Teuling', helveczian: 'Teuling' } },
  { forename: { male: 'Koen', female: 'Lieve' }, surname: { native: 'Thijssen', helveczian: 'Thijssen' } },
  { forename: { male: 'Koenraad', female: 'Lillian' }, surname: { native: 'Thyssen', helveczian: 'Thyssen' } },
  { forename: { male: 'Koos', female: 'Lina' }, surname: { native: 'Timmerman', helveczian: 'Timmerman' } },
  { forename: { male: 'Lambertus', female: 'Loes' }, surname: { native: 'Troelstra', helveczian: 'Troelstra' } },
  { forename: { male: 'Lars', female: 'Lonneke' }, surname: { native: 'Tuinstra', helveczian: 'Tuinstra' } },
  { forename: { male: 'Leendert', female: 'Lotte' }, surname: { native: 'Veenstra', helveczian: 'Veenstra' } },
  { forename: { male: 'Leonardus', female: 'Lowiena' }, surname: { native: 'Venema', helveczian: 'Venema' } },
  { forename: { male: 'Lieve', female: 'Maaike' }, surname: { native: 'Vinke', helveczian: 'Vinke' } },
  { forename: { male: 'Linus', female: 'Maartje' }, surname: { native: 'Visser', helveczian: 'Visser' } },
  { forename: { male: 'Lodewijk', female: 'Manon' }, surname: { native: 'Vos', helveczian: 'Vos' } },
  { forename: { male: 'Ludovicus', female: 'Margaretha' }, surname: { native: 'Vos', helveczian: 'Vos' } },
  { forename: { male: 'Lukas', female: 'Margaux' }, surname: { native: 'Vroom', helveczian: 'Vroom' } },
  { forename: { male: 'Luuk', female: 'Margo' }, surname: { native: 'Westra', helveczian: 'Westra' } },
  { forename: { male: 'Maarten', female: 'Margriet' }, surname: { native: 'Wiersma', helveczian: 'Wiersma' } },
  { forename: { male: 'Maikel', female: 'Maria' }, surname: { native: 'Willems', helveczian: 'Willems' } },
  { forename: { male: 'Marijn', female: 'Marianne' }, surname: { native: 'Willemsen', helveczian: 'Willemsen' } },
  { forename: { male: 'Martijn', female: 'Marieke' }, surname: { native: 'Zijlstra', helveczian: 'Zijlstra' } },
  { forename: { male: 'Mattheus', female: 'Marije' }, surname: { native: 'Zuidema', helveczian: 'Zuidema' } },
  { forename: { male: 'Matthijs', female: 'Marijke' }, surname: { native: 'de Boer', helveczian: 'de Boer' } },
  { forename: { male: 'Maurits', female: 'Marijn' }, surname: { native: 'de Bruijn', helveczian: 'de Bruijn' } },
  { forename: { male: 'Melis', female: 'Mariska' }, surname: { native: 'de Clercq', helveczian: 'de Clercq' } },
  { forename: { male: 'Melvin', female: 'Marja' }, surname: { native: 'de Croo', helveczian: 'de Croo' } },
  { forename: { male: 'Niek', female: 'Marjan' }, surname: { native: 'de Cuyper', helveczian: 'de Cuyper' } },
  { forename: { male: 'Norbert', female: 'Marjo' }, surname: { native: 'de Fauw', helveczian: 'de Fauw' } },
  { forename: { male: 'Okkie', female: 'Marjolein' }, surname: { native: 'de Graaf', helveczian: 'de Graaf' } },
  { forename: { male: 'Olaf', female: 'Marleen' }, surname: { native: 'de Groot', helveczian: 'de Groot' } },
  { forename: { male: 'Onno', female: 'Marlies' }, surname: { native: 'de Haan', helveczian: 'de Haan' } },
  { forename: { male: 'Otto', female: 'Marloes' }, surname: { native: 'de Haas', helveczian: 'de Haas' } },
  { forename: { male: 'Paulus', female: 'Marta' }, surname: { native: 'de Jaager', helveczian: 'de Jaager' } },
  { forename: { male: 'Pepijn', female: 'Meike' }, surname: { native: 'de Jong', helveczian: 'de Jong' } },
  { forename: { male: 'Philip', female: 'Melanie' }, surname: { native: 'de Jong', helveczian: 'de Jong' } },
  { forename: { male: 'Pieter', female: 'Merel' }, surname: { native: 'de Koning', helveczian: 'de Koning' } },
  { forename: { male: 'Pim', female: 'Mieke' }, surname: { native: 'de Kuiper', helveczian: 'de Kuiper' } },
  { forename: { male: 'Quirijn', female: 'Mirjam' }, surname: { native: 'de Kuyper', helveczian: 'de Kuyper' } },
  { forename: { male: 'Reinier', female: 'Myrthe' }, surname: { native: 'de Lange', helveczian: 'de Lange' } },
  { forename: { male: 'Reinout', female: 'Nadine' }, surname: { native: 'de Lange', helveczian: 'de Lange' } },
  { forename: { male: 'Rembrandt', female: 'Nanne' }, surname: { native: 'de Vries', helveczian: 'de Vries' } },
  { forename: { male: 'Rens', female: 'Natalie' }, surname: { native: 'de Wees', helveczian: 'de Wees' } },
  { forename: { male: 'Rien', female: 'Nathalie' }, surname: { native: 'de Windt', helveczian: 'de Windt' } },
  { forename: { male: 'Rik', female: 'Nel' }, surname: { native: 'de Wit', helveczian: 'de Wit' } },
  { forename: { male: 'Roelant', female: 'Nettie' }, surname: { native: 'den Koning', helveczian: 'den Koning' } },
  { forename: { male: 'Roelof', female: 'Nienke' }, surname: { native: 'van Aitzema', helveczian: 'van Aitzema' } },
  { forename: { male: 'Rombout', female: 'Olga' }, surname: { native: 'van Beek', helveczian: 'van Beek' } },
  { forename: { male: 'Romeyn', female: 'Paula' }, surname: { native: 'van Buskirk', helveczian: 'van Buskirk' } },
  {
    forename: { male: 'Rutger', female: 'Paulien' },
    surname: { native: 'van Coevorden', helveczian: 'van Coevorden' },
  },
  { forename: { male: 'Ruud', female: 'Petronella' }, surname: { native: 'van Deijck', helveczian: 'van Deijck' } },
  { forename: { male: 'Sebastiaan', female: 'Puck' }, surname: { native: 'van Dijk', helveczian: 'van Dijk' } },
  { forename: { male: 'Sjaak', female: 'Ria' }, surname: { native: 'van Dijk', helveczian: 'van Dijk' } },
  { forename: { male: 'Sjoerd', female: 'Rie' }, surname: { native: 'van Hoebeek', helveczian: 'van Hoebeek' } },
  { forename: { male: 'Stefaan', female: 'Sanne' }, surname: { native: 'van Leeuwen', helveczian: 'van Leeuwen' } },
  { forename: { male: 'Stijn', female: 'Saskia' }, surname: { native: 'van Rijn', helveczian: 'van Rijn' } },
  { forename: { male: 'Sven', female: 'Sophie' }, surname: { native: 'van Sittart', helveczian: 'van Sittart' } },
  { forename: { male: 'Teun', female: 'Suzanne' }, surname: { native: 'van Vliet', helveczian: 'van Vliet' } },
  { forename: { male: 'Thaddeus', female: 'Teuntje' }, surname: { native: 'van Wees', helveczian: 'van Wees' } },
  { forename: { male: 'Theodoros', female: 'Theresia' }, surname: { native: 'van Zijl', helveczian: 'van Zijl' } },
  { forename: { male: 'Theunis', female: 'Tineke' }, surname: { native: 'van Zutphen', helveczian: 'van Zutphen' } },
  { forename: { male: 'Thijmen', female: 'Toine' }, surname: { native: 'van de Hoek', helveczian: 'van de Hoek' } },
  { forename: { male: 'Thijs', female: 'Tonie' }, surname: { native: 'van den Berg', helveczian: 'van den Berg' } },
  {
    forename: { male: 'Tielman', female: 'Toos' },
    surname: { native: 'van den Heuvel', helveczian: 'van den Heuvel' },
  },
  { forename: { male: 'Tijs', female: 'Trijn' }, surname: { native: 'van der Berg', helveczian: 'van der Berg' } },
  { forename: { male: 'Tjeerd', female: 'Truus' }, surname: { native: 'van der Bijl', helveczian: 'van der Bijl' } },
  { forename: { male: 'Tobias', female: 'Valerie' }, surname: { native: 'van der Boor', helveczian: 'van der Boor' } },
  { forename: { male: 'Toine', female: 'Vicky' }, surname: { native: 'van der Byl', helveczian: 'van der Byl' } },
  { forename: { male: 'Tonie', female: 'Viola' }, surname: { native: 'van der Heide', helveczian: 'van der Heide' } },
  {
    forename: { male: 'Valentijn', female: 'Wilhelmina' },
    surname: { native: 'van der Kleij', helveczian: 'van der Kleij' },
  },
  {
    forename: { male: 'Walraven', female: 'Willeke' },
    surname: { native: 'van der Linden', helveczian: 'van der Linden' },
  },
  { forename: { male: 'Wiebe', female: 'Willemijn' }, surname: { native: 'van der Meer', helveczian: 'van der Meer' } },
  {
    forename: { male: 'Willem', female: 'Willemina' },
    surname: { native: 'van der Molen', helveczian: 'van der Molen' },
  },
  { forename: { male: 'Wisse', female: 'Wilma' }, surname: { native: 'van der Vuurst', helveczian: 'van der Vuurst' } },
  {
    forename: { male: 'Xander', female: 'Yvette' },
    surname: { native: 'van der Westhuizen', helveczian: 'van der Westhuizen' },
  },
  { forename: { male: 'Zeger', female: 'Yvonne' }, surname: { native: 'van het Hoff', helveczian: 'van het Hoff' } },
];
