export const ItalianNames = [
  { forename: { male: 'Adamo', female: 'Adriana' }, surname: { native: 'Abagio', helveczian: 'Alfieri' } },
  { forename: { male: 'Agnolo', female: 'Agnella' }, surname: { native: 'Acerbi', helveczian: 'Ambrosini' } },
  { forename: { male: 'Agostino', female: 'Agnese' }, surname: { native: 'Acordolo', helveczian: 'Ballinari' } },
  { forename: { male: 'Alberico', female: 'Albina' }, surname: { native: 'Albarenno', helveczian: 'Balzari' } },
  { forename: { male: 'Aldo', female: 'Alessandra' }, surname: { native: 'Albergati', helveczian: 'Barenco' } },
  { forename: { male: 'Alessandro', female: 'Alessia' }, surname: { native: 'Albiso', helveczian: 'Beltrami' } },
  { forename: { male: 'Alessio', female: 'Annamaria' }, surname: { native: 'Augeri', helveczian: 'Berla' } },
  { forename: { male: 'Ambrogio', female: 'Antonella' }, surname: { native: 'Avonal', helveczian: 'Bernardi' } },
  { forename: { male: 'Andrea', female: 'Antonia' }, surname: { native: 'Babilonio', helveczian: 'Bernasocchi' } },
  { forename: { male: 'Angelo', female: 'Aurelia' }, surname: { native: 'Baldovinetti', helveczian: 'Bertina' } },
  { forename: { male: 'Antonio', female: 'Barbara' }, surname: { native: 'Barba', helveczian: 'Besler' } },
  { forename: { male: 'Armando', female: 'Beatrice' }, surname: { native: 'Barbachollo', helveczian: 'Biasca' } },
  { forename: { male: 'Arnaldo', female: 'Bella' }, surname: { native: 'Barbamachollo', helveczian: 'Bodinoli' } },
  { forename: { male: 'Arrigo', female: 'Bianca' }, surname: { native: 'Barbazini', helveczian: 'Bonoli' } },
  { forename: { male: 'Arturo', female: 'Camilla' }, surname: { native: 'Barberan', helveczian: 'Bonzanigo' } },
  { forename: { male: 'Averardo', female: 'Carlotta' }, surname: { native: 'Barbigia', helveczian: 'Borghi' } },
  {
    forename: { male: 'Bartolomeo', female: 'Cassandra' },
    surname: { native: 'Barozzi', helveczian: 'Borgo-Caratti' },
  },
  { forename: { male: 'Bastiano', female: 'Cecilia' }, surname: { native: 'Bellego', helveczian: 'Brentini' } },
  { forename: { male: 'Benedetto', female: 'Chiara' }, surname: { native: 'Bellini', helveczian: 'Bruga' } },
  { forename: { male: 'Benozzo', female: 'Cristina' }, surname: { native: 'Bernasconi', helveczian: 'Bulloni' } },
  { forename: { male: 'Bertino', female: 'Donatella' }, surname: { native: 'Bianchi', helveczian: 'Calanchini' } },
  { forename: { male: 'Bindo', female: 'Eleanora' }, surname: { native: 'Bieri', helveczian: 'Capezzoli' } },
  { forename: { male: 'Bruno', female: 'Elisabetta' }, surname: { native: 'Bondimier', helveczian: 'Carmine' } },
  { forename: { male: 'Camillo', female: 'Euphemia' }, surname: { native: 'Buglione', helveczian: 'Cattaneo' } },
  { forename: { male: 'Carlo', female: 'Fabrizia' }, surname: { native: 'Calandrini', helveczian: 'Cauzza' } },
  { forename: { male: 'Cesare', female: 'Federica' }, surname: { native: 'Calbi', helveczian: 'Christofanini' } },
  { forename: { male: 'Chimento', female: 'Fiametta' }, surname: { native: 'Calbo', helveczian: 'Cippá' } },
  { forename: { male: 'Claudio', female: 'Filippa' }, surname: { native: 'Calderara', helveczian: 'Cusa' } },
  { forename: { male: 'Cristoforo', female: 'Flavia' }, surname: { native: 'Caldogne', helveczian: 'Delgrande' } },
  { forename: { male: 'Domenico', female: 'Francesca' }, surname: { native: 'Callocci', helveczian: 'Dolcini' } },
  { forename: { male: 'Donato', female: 'Franceschina' }, surname: { native: 'Calvane', helveczian: 'Farinelli' } },
  { forename: { male: 'Ennio', female: 'Francheta' }, surname: { native: 'Calvenzano', helveczian: 'Flori' } },
  { forename: { male: 'Enrico', female: 'Gianna' }, surname: { native: 'Calza', helveczian: 'Gabani' } },
  { forename: { male: 'Ercole', female: 'Ginevra' }, surname: { native: 'Canepa', helveczian: 'Galli' } },
  { forename: { male: 'Ernesto', female: 'Giovanna' }, surname: { native: 'Contarini', helveczian: 'Ghisla' } },
  { forename: { male: 'Fabrizio', female: 'Giulia' }, surname: { native: 'Corner', helveczian: 'Gianini' } },
  { forename: { male: 'Fausto', female: 'Giulietta' }, surname: { native: 'Crivelli', helveczian: 'Giovanetti' } },
  { forename: { male: 'Ferdinando', female: 'Gloria' }, surname: { native: 'da Leze', helveczian: 'Grossi' } },
  { forename: { male: 'Fiorentino', female: 'Griselda' }, surname: { native: 'da Vigo', helveczian: 'Guglielmini' } },
  { forename: { male: 'Francesco', female: 'Helena' }, surname: { native: 'de Abondiolis', helveczian: 'Guidi' } },
  { forename: { male: 'Fulvio', female: 'Ilaria' }, surname: { native: 'de Accora', helveczian: 'Guidinetti' } },
  { forename: { male: 'Gaetano', female: 'Imelda' }, surname: { native: 'de Alberinis', helveczian: 'Laffranchi' } },
  { forename: { male: 'Gasparo', female: 'Iolanda' }, surname: { native: 'de Albiate', helveczian: 'Laffranchini' } },
  { forename: { male: 'Giacinto', female: 'Ippolita' }, surname: { native: 'de Calis', helveczian: 'Lavizzari' } },
  { forename: { male: 'Giacomo', female: 'Isabella' }, surname: { native: 'de Calvino', helveczian: 'Lentini' } },
  { forename: { male: 'Giancarlo', female: 'Isotta' }, surname: { native: 'de Fidellis', helveczian: 'Leona' } },
  { forename: { male: 'Gianfrancesco', female: 'Julia' }, surname: { native: 'de Filago', helveczian: 'Luis' } },
  { forename: { male: 'Gianluigi', female: 'Laura' }, surname: { native: 'de Fino', helveczian: 'Lussi' } },
  { forename: { male: 'Gilberto', female: 'Lauretta' }, surname: { native: 'de Priuli', helveczian: 'Malaguerra' } },
  { forename: { male: 'Gioffre', female: 'Letizia' }, surname: { native: 'de Rossi', helveczian: 'Maletti' } },
  { forename: { male: 'Giorgio', female: 'Lidia' }, surname: { native: 'Donado', helveczian: 'Mantelli' } },
  { forename: { male: 'Giovanni', female: 'Livia' }, surname: { native: 'Falier', helveczian: 'Mariotti' } },
  { forename: { male: 'Girolamo', female: 'Lorena' }, surname: { native: 'Farnese', helveczian: 'Martignoli' } },
  { forename: { male: 'Giuseppe', female: 'Lorenza' }, surname: { native: 'Filiarchi', helveczian: 'Mazzucchelli' } },
  { forename: { male: 'Guglielmo', female: 'Loretta' }, surname: { native: 'Fiolario', helveczian: 'Micheletti' } },
  { forename: { male: 'Guido', female: 'Lucia' }, surname: { native: 'Fioravanti', helveczian: 'Minetta' } },
  { forename: { male: 'Jacopo', female: 'Lucrezia' }, surname: { native: 'Fiorino', helveczian: 'Minotti' } },
  { forename: { male: 'Lazzaro', female: 'Luisa' }, surname: { native: 'Fonte', helveczian: 'Molinari' } },
  { forename: { male: 'Lodovico', female: 'Madelena' }, surname: { native: 'Foscarini', helveczian: 'Morelli' } },
  { forename: { male: 'Lorenzo', female: 'Marcella' }, surname: { native: 'Gioffre', helveczian: 'Moretti' } },
  { forename: { male: 'Luca', female: 'Maria' }, surname: { native: 'Giustiniani', helveczian: 'Muggiasca' } },
  { forename: { male: 'Luciano', female: 'Marietta' }, surname: { native: 'Gradenigo', helveczian: 'Nadi' } },
  { forename: { male: 'Luigi', female: 'Marissa' }, surname: { native: 'Grimaldi', helveczian: 'Negrini' } },
  { forename: { male: 'Marcello', female: 'Marta' }, surname: { native: 'Grimani', helveczian: 'Odone' } },
  { forename: { male: 'Marco', female: 'Martinella' }, surname: { native: 'Gritti', helveczian: 'Ostini' } },
  { forename: { male: 'Mariano', female: 'Melissa' }, surname: { native: 'La Tella', helveczian: 'Pacciorini' } },
  { forename: { male: 'Mario', female: 'Monica' }, surname: { native: 'Lanzone', helveczian: 'Palla' } },
  { forename: { male: 'Massimo', female: 'Morena' }, surname: { native: 'Larocca', helveczian: 'Paolini' } },
  { forename: { male: 'Matteo', female: 'Morella' }, surname: { native: 'Lonero', helveczian: 'Pedotti' } },
  { forename: { male: 'Maurizio', female: 'Nezetta' }, surname: { native: 'Longo', helveczian: 'Pedrazzoli' } },
  { forename: { male: 'Moreno', female: 'Nina' }, surname: { native: 'Loredan', helveczian: 'Pellanda' } },
  { forename: { male: 'Niccolo', female: 'Olimpia' }, surname: { native: 'Luppi', helveczian: 'Pellini' } },
  { forename: { male: 'Nunzio', female: 'Olivia' }, surname: { native: 'Marcello', helveczian: 'Peretti' } },
  { forename: { male: 'Orlando', female: 'Ornelia' }, surname: { native: 'Marchesani', helveczian: 'Pessi' } },
  { forename: { male: 'Ottavio', female: 'Paola' }, surname: { native: 'Marin', helveczian: 'Pini' } },
  { forename: { male: 'Pandolfo', female: 'Patrizia' }, surname: { native: 'Mariotti', helveczian: 'Ponzio' } },
  { forename: { male: 'Pasquale', female: 'Paula' }, surname: { native: 'Mauroceno', helveczian: 'Raspini' } },
  { forename: { male: 'Patrizio', female: 'Raffaella' }, surname: { native: 'Mazzara', helveczian: 'Ravizza' } },
  { forename: { male: 'Pierluigi', female: 'Regina' }, surname: { native: 'Memo', helveczian: 'Re' } },
  { forename: { male: 'Pietro', female: 'Renata' }, surname: { native: 'Menditto', helveczian: 'Respini' } },
  { forename: { male: 'Raimondo', female: 'Roberta' }, surname: { native: 'Mocenigo', helveczian: 'Rossi' } },
  { forename: { male: 'Riccardo', female: 'Romana' }, surname: { native: 'Monteleone', helveczian: 'Rusconi' } },
  { forename: { male: 'Ruggiero', female: 'Rosalia' }, surname: { native: 'Morini', helveczian: 'Sacchi' } },
  { forename: { male: 'Sabatino', female: 'Rosina' }, surname: { native: 'Morosini', helveczian: 'Sacchi' } },
  { forename: { male: 'Salvadore', female: 'Rossella' }, surname: { native: 'Pasqua', helveczian: 'Sartorio' } },
  { forename: { male: 'Sebastiano', female: 'Roxana' }, surname: { native: 'Pellitteri', helveczian: 'Scarpellini' } },
  { forename: { male: 'Sergio', female: 'Sandra' }, surname: { native: 'Porzio', helveczian: 'Scolari' } },
  { forename: { male: 'Sigismondo', female: 'Serafina' }, surname: { native: 'Querini', helveczian: 'Snozzi' } },
  { forename: { male: 'Silvestro', female: 'Sibilla' }, surname: { native: 'Riccoboni', helveczian: 'Solari' } },
  { forename: { male: 'Silvio', female: 'Silvia' }, surname: { native: 'Roncone', helveczian: 'Taddei' } },
  { forename: { male: 'Spinello', female: 'Simona' }, surname: { native: 'Rosso', helveczian: 'Taragnoli' } },
  { forename: { male: 'Stefano', female: 'Simonetta' }, surname: { native: 'Scalera', helveczian: 'Tatti' } },
  { forename: { male: 'Stoldo', female: 'Sophia' }, surname: { native: 'Spizega', helveczian: 'Tognacca' } },
  { forename: { male: 'Taddeo', female: 'Stella' }, surname: { native: 'Tessitore', helveczian: 'Tonini' } },
  { forename: { male: 'Tommaso', female: 'Valentina' }, surname: { native: 'Trevisan', helveczian: 'Traversi' } },
  { forename: { male: 'Ubaldo', female: 'Valeria' }, surname: { native: 'Vellucci', helveczian: 'Valentini' } },
  { forename: { male: 'Uberto', female: 'Verona' }, surname: { native: 'Vetrone', helveczian: 'Vanazzi' } },
  { forename: { male: 'Ugo', female: 'Veronica' }, surname: { native: 'Vitelli', helveczian: 'Varrone' } },
  { forename: { male: 'Umberto', female: 'Vincenza' }, surname: { native: 'Zambrano', helveczian: 'Zanetti' } },
  { forename: { male: 'Virgilio', female: 'Vittoria' }, surname: { native: 'Zorzi', helveczian: 'Zanini' } },
];
