export const SwedishNames = [
  { forename: { male: 'Lars', female: 'Anna' }, surname: { native: 'Larsson', helveczian: 'Larsson' } },
  { forename: { male: 'Mikael', female: 'Eva' }, surname: { native: 'Mikaelson', helveczian: 'Mikaelson' } },
  { forename: { male: 'Anders', female: 'Maria' }, surname: { native: 'Andersson', helveczian: 'Andersson' } },
  { forename: { male: 'Johan', female: 'Karin' }, surname: { native: 'Johanson', helveczian: 'Johanson' } },
  { forename: { male: 'Erik', female: 'Kristina' }, surname: { native: 'Erikson', helveczian: 'Erikson' } },
  { forename: { male: 'Per', female: 'Sara' }, surname: { native: 'Person', helveczian: 'Person' } },
  { forename: { male: 'Karl', female: 'Lena' }, surname: { native: 'Karlson', helveczian: 'Karlson' } },
  { forename: { male: 'Peter', female: 'Emma' }, surname: { native: 'Peterson', helveczian: 'Peterson' } },
  { forename: { male: 'Thomas', female: 'Kerstin' }, surname: { native: 'Thomasson', helveczian: 'Thomasson' } },
  { forename: { male: 'Jan', female: 'Ingrid' }, surname: { native: 'Janson', helveczian: 'Janson' } },
  { forename: { male: 'Daniel', female: 'Marie' }, surname: { native: 'Danielson', helveczian: 'Danielson' } },
  { forename: { male: 'Fredrik', female: 'Malin' }, surname: { native: 'Fredrikson', helveczian: 'Fredrikson' } },
  { forename: { male: 'Hans', female: 'Jenny' }, surname: { native: 'Hansson', helveczian: 'Hansson' } },
  { forename: { male: 'Andreas', female: 'Annika' }, surname: { native: 'Andreasson', helveczian: 'Andreasson' } },
  { forename: { male: 'Stefan', female: 'Hanna' }, surname: { native: 'Stefanson', helveczian: 'Stefanson' } },
  { forename: { male: 'Mohamed', female: 'Linda' }, surname: { native: 'Mohamedson', helveczian: 'Mohamedson' } },
  { forename: { male: 'Mats', female: 'Birgitta' }, surname: { native: 'Matsson', helveczian: 'Matsson' } },
  { forename: { male: 'Marcus', female: 'Susanne' }, surname: { native: 'Marcusson', helveczian: 'Marcusson' } },
  { forename: { male: 'Mattias', female: 'Elin' }, surname: { native: 'Mattiasson', helveczian: 'Mattiasson' } },
  { forename: { male: 'Magnus', female: 'Monica' }, surname: { native: 'Magnusson', helveczian: 'Magnusson' } },
  { forename: { male: 'Bengt', female: 'Inger' }, surname: { native: 'Bengtson', helveczian: 'Bengtson' } },
  { forename: { male: 'Jonas', female: 'Sofia' }, surname: { native: 'Jonasson', helveczian: 'Jonasson' } },
  { forename: { male: 'Oskar', female: 'Johanna' }, surname: { native: 'Oskarson', helveczian: 'Oskarson' } },
  {
    forename: { male: 'Alexander', female: 'Carina' },
    surname: { native: 'Alexanderson', helveczian: 'Alexanderson' },
  },
  { forename: { male: 'Niklas', female: 'Elisabeth' }, surname: { native: 'Niklasson', helveczian: 'Niklasson' } },
  { forename: { male: 'Martin', female: 'Ulla' }, surname: { native: 'Martinson', helveczian: 'Martinson' } },
  { forename: { male: 'Bo', female: 'Julia' }, surname: { native: 'Boson', helveczian: 'Boson' } },
  { forename: { male: 'Nils', female: 'Katarina' }, surname: { native: 'Nilsson', helveczian: 'Nilsson' } },
  { forename: { male: 'Patrik', female: 'Linnéa' }, surname: { native: 'Patrikson', helveczian: 'Patrikson' } },
  { forename: { male: 'Viktor', female: 'Emelie' }, surname: { native: 'Viktorson', helveczian: 'Viktorson' } },
  { forename: { male: 'Björn', female: 'Ida' }, surname: { native: 'Björnson', helveczian: 'Björnson' } },
  { forename: { male: 'Leif', female: 'Helena' }, surname: { native: 'Leifson', helveczian: 'Leifson' } },
  { forename: { male: 'David', female: 'Camilla' }, surname: { native: 'Davidson', helveczian: 'Davidson' } },
  { forename: { male: 'Sven', female: 'Åsa' }, surname: { native: 'Svenson', helveczian: 'Svenson' } },
  { forename: { male: 'Henrik', female: 'Anette' }, surname: { native: 'Henrikson', helveczian: 'Henrikson' } },
  { forename: { male: 'Filip', female: 'Sandra' }, surname: { native: 'Filipson', helveczian: 'Filipson' } },
  { forename: { male: 'Joakim', female: 'Gunilla' }, surname: { native: 'Joakimson', helveczian: 'Joakimson' } },
  { forename: { male: 'Christer', female: 'Anita' }, surname: { native: 'Christerson', helveczian: 'Christerson' } },
  { forename: { male: 'Ulf', female: 'Marianne' }, surname: { native: 'Ulfson', helveczian: 'Ulfson' } },
  { forename: { male: 'Emil', female: 'Margareta' }, surname: { native: 'Emilson', helveczian: 'Emilson' } },
  { forename: { male: 'Simon', female: 'Anneli' }, surname: { native: 'Simonson', helveczian: 'Simonson' } },
  {
    forename: { male: 'Christoffer', female: 'Amanda' },
    surname: { native: 'Christofferson', helveczian: 'Christofferson' },
  },
  { forename: { male: 'Anton', female: 'Maja' }, surname: { native: 'Antonson', helveczian: 'Antonson' } },
  { forename: { male: 'Gustav', female: 'Ann' }, surname: { native: 'Gustavson', helveczian: 'Gustavson' } },
  { forename: { male: 'Robert', female: 'Therese' }, surname: { native: 'Robertson', helveczian: 'Robertson' } },
  { forename: { male: 'Tommy', female: 'Josefin' }, surname: { native: 'Tommyson', helveczian: 'Tommyson' } },
  { forename: { male: 'Kjell', female: 'Cecilia' }, surname: { native: 'Kjellson', helveczian: 'Kjellson' } },
  {
    forename: { male: 'Christian', female: 'Jessica' },
    surname: { native: 'Christianson', helveczian: 'Christianson' },
  },
  { forename: { male: 'William', female: 'Helen' }, surname: { native: 'Williamson', helveczian: 'Williamson' } },
  { forename: { male: 'Lucas', female: 'Lisa' }, surname: { native: 'Lucasson', helveczian: 'Lucasson' } },
  { forename: { male: 'Rickard', female: 'Caroline' }, surname: { native: 'Rickardson', helveczian: 'Rickardson' } },
  { forename: { male: 'Håkan', female: 'Matilda' }, surname: { native: 'Håkanson', helveczian: 'Håkanson' } },
  { forename: { male: 'Göran', female: 'Barbro' }, surname: { native: 'Göranson', helveczian: 'Göranson' } },
  { forename: { male: 'Rolf', female: 'Frida' }, surname: { native: 'Rolfson', helveczian: 'Rolfson' } },
  { forename: { male: 'Adam', female: 'Ulrika' }, surname: { native: 'Adamson', helveczian: 'Adamson' } },
  { forename: { male: 'Lennart', female: 'Elsa' }, surname: { native: 'Lennartson', helveczian: 'Lennartson' } },
  { forename: { male: 'Jakob', female: 'Siv' }, surname: { native: 'Jakobson', helveczian: 'Jakobson' } },
  { forename: { male: 'Jonathan', female: 'Alice' }, surname: { native: 'Jonathanson', helveczian: 'Jonathanson' } },
  { forename: { male: 'Robin', female: 'Madeleine' }, surname: { native: 'Robinson', helveczian: 'Robinson' } },
  {
    forename: { male: 'Sebastian', female: 'Rebecca' },
    surname: { native: 'Sebastianson', helveczian: 'Sebastianson' },
  },
  { forename: { male: 'Tobias', female: 'Klara' }, surname: { native: 'Tobiasson', helveczian: 'Tobiasson' } },
  { forename: { male: 'Stig', female: 'Ebba' }, surname: { native: 'Stigson', helveczian: 'Stigson' } },
  { forename: { male: 'Elias', female: 'Sofie' }, surname: { native: 'Eliasson', helveczian: 'Eliasson' } },
  { forename: { male: 'John', female: 'Gun' }, surname: { native: 'Johnson', helveczian: 'Johnson' } },
  { forename: { male: 'Axel', female: 'Agneta' }, surname: { native: 'Axelson', helveczian: 'Axelson' } },
  { forename: { male: 'Linus', female: 'Berit' }, surname: { native: 'Linusson', helveczian: 'Linusson' } },
  { forename: { male: 'Kent', female: 'Isabelle' }, surname: { native: 'Kentson', helveczian: 'Kentson' } },
  { forename: { male: 'Oliver', female: 'Lina' }, surname: { native: 'Oliverson', helveczian: 'Oliverson' } },
  { forename: { male: 'Roger', female: 'Pia' }, surname: { native: 'Rogerson', helveczian: 'Rogerson' } },
  { forename: { male: 'Hugo', female: 'Wilma' }, surname: { native: 'Hugoson', helveczian: 'Hugoson' } },
  { forename: { male: 'Isak', female: 'Ella' }, surname: { native: 'Isakson', helveczian: 'Isakson' } },
  { forename: { male: 'Claes', female: 'Yvonne' }, surname: { native: 'Claesson', helveczian: 'Claesson' } },
  { forename: { male: 'Jesper', female: 'Louise' }, surname: { native: 'Jesperson', helveczian: 'Jesperson' } },
  { forename: { male: 'Albin', female: 'Ellen' }, surname: { native: 'Albinson', helveczian: 'Albinson' } },
  { forename: { male: 'Jörgen', female: 'Britt' }, surname: { native: 'Jörgenson', helveczian: 'Jörgenson' } },
  { forename: { male: 'Rasmus', female: 'Astrid' }, surname: { native: 'Rasmusson', helveczian: 'Rasmusson' } },
  { forename: { male: 'Ludvig', female: 'Mona' }, surname: { native: 'Ludvigson', helveczian: 'Ludvigson' } },
  { forename: { male: 'Jimmy', female: 'Moa' }, surname: { native: 'Jimmyson', helveczian: 'Jimmyson' } },
  { forename: { male: 'Max', female: 'Nathalie' }, surname: { native: 'Maxson', helveczian: 'Maxson' } },
  { forename: { male: 'Ali', female: 'Erika' }, surname: { native: 'Alison', helveczian: 'Alison' } },
  { forename: { male: 'Kenneth', female: 'Alexandra' }, surname: { native: 'Kennethson', helveczian: 'Kennethson' } },
  { forename: { male: 'Gunnar', female: 'Emilia' }, surname: { native: 'Gunnarson', helveczian: 'Gunnarson' } },
  { forename: { male: 'Joel', female: 'Viktoria' }, surname: { native: 'Joelson', helveczian: 'Joelson' } },
  { forename: { male: 'Dennis', female: 'Ann-Christin' }, surname: { native: 'Dennisson', helveczian: 'Dennisson' } },
  { forename: { male: 'Johnny', female: 'Olivia' }, surname: { native: 'Johnnyson', helveczian: 'Johnnyson' } },
  { forename: { male: 'Josef', female: 'Alva' }, surname: { native: 'Josefson', helveczian: 'Josefson' } },
  { forename: { male: 'Olof', female: 'Agnes' }, surname: { native: 'Olofson', helveczian: 'Olofson' } },
  { forename: { male: 'Åke', female: 'Felicia' }, surname: { native: 'Åkeson', helveczian: 'Åkeson' } },
  { forename: { male: 'Olle', female: 'Ann-Marie' }, surname: { native: 'Olleson', helveczian: 'Olleson' } },
  { forename: { male: 'Kurt', female: 'Sonja' }, surname: { native: 'Kurtson', helveczian: 'Kurtson' } },
  { forename: { male: 'Liam', female: 'Britt-Marie' }, surname: { native: 'Liamson', helveczian: 'Liamson' } },
  { forename: { male: 'Pontus', female: 'Pernilla' }, surname: { native: 'Pontusson', helveczian: 'Pontusson' } },
  { forename: { male: 'Leo', female: 'Gunnel' }, surname: { native: 'Leoson', helveczian: 'Leoson' } },
  { forename: { male: 'Kevin', female: 'Lovisa' }, surname: { native: 'Kevinson', helveczian: 'Kevinson' } },
  { forename: { male: 'Samuel', female: 'Charlotte' }, surname: { native: 'Samuelson', helveczian: 'Samuelson' } },
  { forename: { male: 'Torbjörn', female: 'Linn' }, surname: { native: 'Torbjörnson', helveczian: 'Torbjörnson' } },
  { forename: { male: 'Felix', female: 'Lisbeth' }, surname: { native: 'Felixson', helveczian: 'Felixson' } },
  { forename: { male: 'Edvin', female: 'Nina' }, surname: { native: 'Edvinson', helveczian: 'Edvinson' } },
  { forename: { male: 'Gabriel', female: 'Rut' }, surname: { native: 'Gabrielson', helveczian: 'Gabrielson' } },
  { forename: { male: 'Arvid', female: 'Mikaela' }, surname: { native: 'Arvidson', helveczian: 'Arvidson' } },
];
