export const FrenchNames = [
  { forename: { male: 'Adenet', female: 'Adele' }, surname: { native: 'Favre', helveczian: 'Ausset' } },
  { forename: { male: 'Agénor', female: 'Agathe' }, surname: { native: 'Affré', helveczian: 'Béchet' } },
  { forename: { male: 'Allain', female: 'Agnes' }, surname: { native: 'Allard', helveczian: 'Béranger' } },
  { forename: { male: 'Ambrose', female: 'Alice' }, surname: { native: 'Allemand', helveczian: 'Bérard' } },
  { forename: { male: 'Anselme', female: 'Amélie' }, surname: { native: 'Arceneaux', helveczian: 'Berdez' } },
  { forename: { male: 'Arnalt', female: 'Angélique' }, surname: { native: 'Astier', helveczian: 'Blanchenay' } },
  { forename: { male: 'Aubin', female: 'Anne' }, surname: { native: 'Bacque', helveczian: 'Blanchet' } },
  { forename: { male: 'Bénoist', female: 'Anne-Marie' }, surname: { native: 'Badeux', helveczian: 'Boisot' } },
  { forename: { male: 'Bernard', female: 'Annes' }, surname: { native: 'Barbet', helveczian: 'Borel' } },
  { forename: { male: 'Bertin', female: 'Annette' }, surname: { native: 'Baudet', helveczian: 'Borgeaud' } },
  { forename: { male: 'Blaise', female: 'Arlette' }, surname: { native: 'Beaumont', helveczian: 'Bossy' } },
  { forename: { male: 'Bossu', female: 'Aurélie' }, surname: { native: 'Beauregard', helveczian: 'Bressenel' } },
  { forename: { male: 'Cédric', female: 'Béatrice' }, surname: { native: 'Berger', helveczian: 'Bridel' } },
  { forename: { male: 'Charles', female: 'Belle' }, surname: { native: 'Besnard', helveczian: 'Burnat' } },
  { forename: { male: 'Claude', female: 'Belsant' }, surname: { native: 'Bittencourt', helveczian: 'Carrard' } },
  { forename: { male: 'Clément', female: 'Benedicta' }, surname: { native: 'Blouet', helveczian: 'Chastellain' } },
  { forename: { male: 'Denis', female: 'Bénédicte' }, surname: { native: 'Boissieu', helveczian: 'Chauvet' } },
  { forename: { male: 'Drouet', female: 'Bertha' }, surname: { native: 'Bonhomme', helveczian: 'Chevallier' } },
  { forename: { male: 'Edmond', female: 'Blanche' }, surname: { native: 'Bossuet', helveczian: 'Conod' } },
  { forename: { male: 'Édouard', female: 'Blanchefleur' }, surname: { native: 'Boulet', helveczian: 'Correvon' } },
  { forename: { male: 'Ernault', female: 'Brigitte' }, surname: { native: 'Bourcier', helveczian: 'Creux' } },
  { forename: { male: 'Étienne', female: 'Camille' }, surname: { native: 'Bourgeois', helveczian: 'Cuénoud' } },
  { forename: { male: 'Fabrice', female: 'Cecilia' }, surname: { native: 'Brazier', helveczian: 'Daccord' } },
  { forename: { male: 'Felix', female: 'Céline' }, surname: { native: 'Bruneau', helveczian: 'de Blonay' } },
  { forename: { male: 'Fernand', female: 'Charlotte' }, surname: { native: 'Carpentier', helveczian: 'de Bons' } },
  { forename: { male: 'Floquart', female: 'Christine' }, surname: { native: 'Carré', helveczian: 'de Cerjat' } },
  { forename: { male: 'Francois', female: 'Claire' }, surname: { native: 'Chapelle', helveczian: 'de Coppet' } },
  { forename: { male: 'Frédéric', female: 'Clara' }, surname: { native: 'Choffard', helveczian: 'de Crousaz' } },
  { forename: { male: 'Gaspard', female: 'Claricia' }, surname: { native: 'Clérisseau', helveczian: 'de Dompierre' } },
  { forename: { male: 'Gaston', female: 'Clémence' }, surname: { native: 'Cochin', helveczian: 'de Joffrey' } },
  { forename: { male: 'Gaultier', female: 'Colette' }, surname: { native: 'Cormier', helveczian: 'de la Harpe' } },
  { forename: { male: 'Gérard', female: 'Danielle' }, surname: { native: 'Cortot', helveczian: 'de Loys' } },
  { forename: { male: 'Gerome', female: 'Delphine' }, surname: { native: 'Coupain', helveczian: 'de Morsier' } },
  { forename: { male: 'Gilbert', female: 'Dominique' }, surname: { native: 'Courbet', helveczian: 'de Roguin' } },
  { forename: { male: 'Gilet', female: 'Dorothée' }, surname: { native: 'Crépin', helveczian: 'Delajoux' } },
  { forename: { male: 'Gilles', female: 'Édith' }, surname: { native: 'Cuvier', helveczian: 'Delavigne' } },
  { forename: { male: 'Guibert', female: 'Eleanor' }, surname: { native: "D'Amboise", helveczian: 'Delisle' } },
  { forename: { male: 'Guieffroy', female: 'Éliane' }, surname: { native: 'de Périgon', helveczian: 'Despland' } },
  { forename: { male: 'Guillaume', female: 'Elisabeth' }, surname: { native: 'de Venteillon', helveczian: 'Destraz' } },
  { forename: { male: 'Guiot', female: 'Élodie' }, surname: { native: 'De Verley', helveczian: 'Doxat' } },
  { forename: { male: 'Guy', female: 'Emma' }, surname: { native: 'De Villepin', helveczian: 'Duplessis' } },
  { forename: { male: 'Heliot', female: 'Eugénie' }, surname: { native: 'Delannoy', helveczian: 'Dupuget' } },
  { forename: { male: 'Hiérome', female: 'Eva' }, surname: { native: 'Delaplace', helveczian: 'Duthon' } },
  { forename: { male: 'Hilaire', female: 'Éve' }, surname: { native: 'des Lys', helveczian: 'Duvoisin' } },
  { forename: { male: 'Honoré', female: 'Fleurette' }, surname: { native: 'Dimont', helveczian: 'Fatio' } },
  { forename: { male: 'Huget', female: 'Florine' }, surname: { native: 'Droz', helveczian: 'Favrat' } },
  { forename: { male: 'Hugh', female: 'Francoise' }, surname: { native: 'du Marais', helveczian: 'Fevot' } },
  { forename: { male: 'Hughes', female: 'Geneviéve' }, surname: { native: 'Duchemin', helveczian: 'Fraisse' } },
  { forename: { male: 'Hugo', female: 'Géraldine' }, surname: { native: 'Fouché', helveczian: 'Gantin' } },
  { forename: { male: 'Huguet', female: 'Gillota' }, surname: { native: 'Gachet', helveczian: 'Gaudard' } },
  { forename: { male: 'Imbert', female: 'Giselle' }, surname: { native: 'Gérin', helveczian: 'Gendroz' } },
  { forename: { male: 'Jacob', female: 'Gisla' }, surname: { native: 'Girardot', helveczian: 'Gilliard' } },
  { forename: { male: 'Jacques', female: 'Godelina' }, surname: { native: 'Gounelle', helveczian: 'Grivel' } },
  { forename: { male: 'Jacquet', female: 'Helena' }, surname: { native: 'Granet', helveczian: 'Groux' } },
  { forename: { male: 'Jaquemin', female: 'Heloise' }, surname: { native: 'Granier', helveczian: 'Guex' } },
  { forename: { male: 'Jean', female: 'Hermine' }, surname: { native: 'Grenier', helveczian: 'Henrioud' } },
  { forename: { male: 'Jean-XX', female: 'Isabel' }, surname: { native: 'Jacquier', helveczian: 'Hugonnet' } },
  { forename: { male: 'Jean-XX', female: 'Jaqueline' }, surname: { native: 'Jeannin', helveczian: 'Husson' } },
  { forename: { male: 'Jean-XX', female: 'Jeanne' }, surname: { native: 'Kléber', helveczian: 'La Salle' } },
  { forename: { male: 'Jean-XX', female: 'Jeannette' }, surname: { native: 'Lafaille', helveczian: 'Lambert' } },
  { forename: { male: 'Jehan', female: 'Joëlle' }, surname: { native: 'Laffitte', helveczian: 'Leresche' } },
  { forename: { male: 'Julien', female: 'Jolene' }, surname: { native: 'Lalande', helveczian: 'Maillard' } },
  { forename: { male: 'Justin', female: 'Julie' }, surname: { native: 'Lavaud', helveczian: 'Mandrot' } },
  { forename: { male: 'Lazare', female: 'Juliette' }, surname: { native: 'Lazard', helveczian: 'Marcuard' } },
  { forename: { male: 'Lothaire', female: 'Justine' }, surname: { native: 'le Chaudronnier', helveczian: 'Maret' } },
  { forename: { male: 'Louis', female: 'Leonore' }, surname: { native: 'le Morve', helveczian: 'Masset' } },
  { forename: { male: 'Loys', female: 'Lucie' }, surname: { native: 'Lecocq', helveczian: 'Mercier' } },
  { forename: { male: 'Luc', female: 'Madelaine' }, surname: { native: 'Leroux', helveczian: 'Michod' } },
  { forename: { male: 'Marc', female: 'Manon' }, surname: { native: 'Levasseur', helveczian: 'Monnerat' } },
  { forename: { male: 'Marcel', female: 'Marceline' }, surname: { native: 'Lévesque', helveczian: 'Monneron' } },
  { forename: { male: 'Mathelot', female: 'Margot' }, surname: { native: 'Levett', helveczian: 'Monnier' } },
  { forename: { male: 'Mathieu', female: 'Marianne' }, surname: { native: 'Loup', helveczian: 'Morel' } },
  { forename: { male: 'Maximillien', female: 'Marie' }, surname: { native: 'Maspier', helveczian: 'Muret' } },
  { forename: { male: 'Médard', female: 'Marie-Claude' }, surname: { native: 'Masson', helveczian: 'Ney' } },
  { forename: { male: 'Michel', female: 'Marine' }, surname: { native: 'Mauvaissoir', helveczian: 'Nicollier' } },
  { forename: { male: 'Nicolaus', female: 'Maryse' }, surname: { native: 'Mazzal', helveczian: 'Panchaud' } },
  { forename: { male: 'Octave', female: 'Matildis' }, surname: { native: 'Ménétries', helveczian: 'Papon' } },
  { forename: { male: 'Odo', female: 'Michelle' }, surname: { native: 'Messier', helveczian: 'Paschoud' } },
  { forename: { male: 'Olivier', female: 'Monique' }, surname: { native: 'Moitessier', helveczian: 'Penel' } },
  { forename: { male: 'Pascal', female: 'Noémie' }, surname: { native: 'Morand', helveczian: 'Péneveyre' } },
  { forename: { male: 'Patrick', female: 'Odette' }, surname: { native: 'Piaget', helveczian: 'Perret' } },
  { forename: { male: 'Paul', female: 'Odile' }, surname: { native: 'Picard', helveczian: 'Peytrignet' } },
  { forename: { male: 'Perrin', female: 'Paulette' }, surname: { native: 'Poussin', helveczian: 'Pilloud' } },
  { forename: { male: 'Philippe', female: 'Pauline' }, surname: { native: 'Quint', helveczian: 'Reboul' } },
  { forename: { male: 'Pierre', female: 'Renée' }, surname: { native: 'Renier', helveczian: 'Régis' } },
  { forename: { male: 'Raoul', female: 'Sabine' }, surname: { native: 'Renou', helveczian: 'Rosset' } },
  { forename: { male: 'Rémy', female: 'Sévérine' }, surname: { native: 'Rochette', helveczian: 'Rossier' } },
  { forename: { male: 'René', female: 'Simone' }, surname: { native: 'Rossignol', helveczian: 'Roulet' } },
  { forename: { male: 'Reynard', female: 'Stéphanie' }, surname: { native: 'Rouanet', helveczian: 'Savary' } },
  { forename: { male: 'Richart', female: 'Suzanne' }, surname: { native: 'Rouzet', helveczian: 'Sordet' } },
  { forename: { male: 'Robert', female: 'Sylvie' }, surname: { native: 'Saint-Méran', helveczian: 'Specht' } },
  { forename: { male: 'Rogier', female: 'Thérése' }, surname: { native: 'Saint-Yves', helveczian: 'Taillens' } },
  { forename: { male: 'Roland', female: 'Valérie' }, surname: { native: 'Seyrés', helveczian: 'Tapernoux' } },
  { forename: { male: 'Simon', female: 'Véronique' }, surname: { native: 'Thévenet', helveczian: 'Tarin' } },
  { forename: { male: 'Stéphane', female: 'Violette' }, surname: { native: 'Thibault', helveczian: 'Tornier' } },
  { forename: { male: 'Theophile', female: 'Vivienne' }, surname: { native: 'Toussaint', helveczian: 'Trincard' } },
  { forename: { male: 'Victor', female: 'Ysoude' }, surname: { native: 'Trintignant', helveczian: 'Villard' } },
  { forename: { male: 'Vincent', female: 'Yvette' }, surname: { native: 'Vaugrenard', helveczian: 'Villommet' } },
  { forename: { male: 'Yves', female: 'Yvonne' }, surname: { native: 'Vérany', helveczian: 'Vulliemin' } },
  { forename: { male: 'Yvonnet', female: 'Zoé' }, surname: { native: 'Villefort', helveczian: 'Willommet' } },
];
